name: Run Python Tests (via conda + mamba)

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.12
        environment-name: motila
        miniforge-variant: Miniforge3  # ✅ stable variant
        activate-environment: motila
        use-mamba: false  # disable broken auto-install

    - name: Install mamba and dependencies
      run: |
        conda install -y -n motila -c conda-forge mamba
        mamba install -y -n motila -c conda-forge \
            numpy scipy matplotlib scikit-image scikit-learn \
            pandas tifffile zarr numcodecs openpyxl xlrd \
            ipywidgets ipykernel ipympl pytest psutil

    - name: Run tests
      run: |
        pytest
