name: Run Python Tests (via conda)

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.12
        environment-name: motila
        use-mamba: true

    - name: Install dependencies
      run: |
        mamba install -y numpy scipy matplotlib scikit-image scikit-learn \
                        pandas tifffile zarr numcodecs openpyxl xlrd \
                        ipywidgets ipykernel ipympl pytest psutil

    - name: Run tests
      run: |
        pytest
